epoch: 3  # Number of training epochs
batch_size: 16  # Batch size for training
eval_batch_size: 32  # Batch size for evaluation
learning_rate: 2e-5  # Learning rate for the optimizer
warmup_proportion: 0.1  # Proportion of training to perform linear learning rate warmup
checkpoint_dir: "Checkpoints"  # Directory to save model checkpoints
save_steps: 500  # Save checkpoint every X updates steps
eval_steps: 100  # Evaluate model on validation set every X steps
logging_steps: 50  # Log training information every X steps