model:
  type: bert  # Set the type of model to use (LSTM or BERT)

training:
  epochs: 10  # Number of training epochs
  batch_size: 32  # Batch size for training
  learning_rate: 0.001  # Learning rate for the optimizer

data:
  train_data_path: /path/to/train_data.csv  # Path to the training data file
  test_data_path: /path/to/test_data.csv  # Path to the test data file

metrics:
  - accuracy  # Metric to evaluate the model performance
  - precision
  - recall
  - f1_score